Dan's Toolshop Server/cs3460/Toolshop/urls.py
from django.urls import path
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views

from . import views

app_name = 'Toolshop'

urlpatterns = [
    # The main website pages
    path('', views.index, name='index'),
    path('account/', views.account_page, name='account'),
    path('reserve/', views.reservation_page, name='reserve'),
    path('reserve/<str:contains>', views.reservation_page_specific, name='reserve_spec'),
    path('tools/', views.tools_page, name='tools'),
    path('projects/', views.projects_page, name='projects'),
    path('contact/', views.contact_page, name='contact'),
    path('error/', views.submission_error, name='error'),
    path('updateError/', views.update_error, name='updateError'),

    # The employee-only section of the website
    path('Employee/', views.reports_main, name='reports_main'),
    path('Employee/users', views.reports_users, name='reports_users'),
    path('Employee/tools/<str:sort_by>', views.reports_tools, name='reports_tools'),
    path('Employee/check_in', views.check_in_page, name='check_in'),
    path('Employee/add_tool', views.add_tool_page, name='add_tool'),
    path('Employee/viewTool/<int:tool_id>', views.specific_tool, name='specific_tool'),
    path('Employee/viewUser/<int:user_id>', views.specific_user, name='specific_user'),
    path('fees/', views.pay_fee_page, name='pay_fee_page'),

    # Actions
    path('makeReservation/<int:id>', views.make_reservation, name='makeReservation'),
    path('submitMessage/', views.submit_message, name='submitMessage'),
    path('updateUserInfo/', views.update_user_info, name='update'),
    path('check_in_tool/<int:tool_id>', views.check_in, name='check_in_tool'),
    path('payfees/<int:user_id>', views.pay_fee, name='pay_fee'),
    path('payperiod/<int:user_id>', views.pay_period, name='pay_period'),


    # Misc urls
    path('redirect/', views.redirection_page, name='redirect'),
    path('database_upload', views.database_upload, name='database_upload'),
]

Dan's Toolshop Server/cs3460/cs3460/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('Toolshop/', include('Toolshop.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

Dan's Toolshop Server/cs3460/Toolshop/models.py
import datetime

from django.contrib.auth.models import User
from django.db import models
from datetime import timedelta
from django.utils import timezone


class Tool(models.Model):
    name = models.CharField(max_length=100)
    category = models.CharField(max_length=100)
    times_checked_out = models.IntegerField()
    cost = models.IntegerField()
    condition = models.TextField(blank=True)  # Blank here means "Can be blank" sometimes.

    is_checked_out = models.BooleanField(default=False)
    date_checked_out = models.DateTimeField(blank=True, null=True)  # Blank\null here means "Can be blank" sometimes.
    who_checked_out = models.CharField(max_length=100, blank=True)  # Blank here means "Can be blank" sometimes.

    def __str__(self):
        return self.name

    def get_due_date(self):
        if self.date_checked_out is None or self.date_checked_out == "":
            return False
        return self.date_checked_out + timedelta(days=7)

    def is_overdue(self):
        if self.date_checked_out is None or self.date_checked_out == "":
            return False
        return self.date_checked_out + timedelta(days=7) < timezone.now()

    def is_condition_listed(self):
        if self.condition == "":
            return False
        return True


class CustomerInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_num = models.CharField(max_length=25)
    address = models.TextField()

    this_period_paid = models.BooleanField(default=False)
    date_paid_until = models.DateTimeField(blank=True, null=True)
    num_currently_checked_out = models.PositiveIntegerField(default=0)
    current_outstanding_balance = models.PositiveIntegerField(blank=True, default=0)

    def is_address_listed(self):
        if self.address == "":
            return False
        return True

    def update_user_status(self):
        if self.date_paid_until is None or self.date_paid_until == "":
            return
        if self.date_paid_until < timezone.now():
            self.this_period_paid = False
            self.date_paid_until = None
            self.save()
            return
        return


class Message(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.CharField(max_length=50)
    subject = models.CharField(max_length=100)
    message = models.CharField(max_length=1000)

    def __str__(self):
        return self.subject

Dan's Toolshop Server/cs3460/Toolshop/views.py
import csv, io
from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.urls import resolve
import datetime
from datetime import timedelta
from django.contrib.auth.models import User
from .models import Tool, CustomerInfo, Message


'''
THIS IS THE FEE WHEN A USER IS LATE RETURNING AN ITEM.  UPDATE IT HERE
'''
LATE_FEE = 5
'''
THIS IS THE NUMBER OF DAYS A SUBSCRIPTION PAYS FOR.  UPDATE IT HERE
'''
SUB_DAYS = 30


def index(request):  # Main page
    context = {}
    return render(request, 'Toolshop/index.html', context)


def projects_page(request):
    context = {}
    return render(request, 'Toolshop/projects.html', context)


def tools_page(request):
    tools_list = Tool.objects.order_by('category')
    context = {
        'tools_list': tools_list
    }
    return render(request, 'Toolshop/tools.html', context)


def contact_page(request):
    context = {}
    return render(request, 'Toolshop/contact.html', context)


def login_page(request):
    context = {}
    return render(request, 'Toolshop/login.html', context)


@login_required
def account_page(request):
    user = request.user
    user.customerinfo.update_user_status()  # Make sure their paid period is not up
    tools_list = Tool.objects.filter(who_checked_out__contains=user.username)
    context = {
        'user': user,
        'tools_list': tools_list
    }
    return render(request, 'Toolshop/account.html', context)


@login_required
def reservation_page(request):
    tools_list = Tool.objects.order_by('category')
    context = {
        'tools_list': tools_list
    }
    return render(request, 'Toolshop/reservation.html', context)


@login_required
def reservation_page_specific(request, contains):  # This page has the results trimmed down by a search query
    if request.POST.get('query') is not None:
        contains = request.POST.get('query')
    tools_list = Tool.objects.filter(name__contains=contains).order_by('category')
    context = {
        'tools_list': tools_list
    }
    return render(request, 'Toolshop/reservation.html', context)

@login_required
def make_reservation(request, id):
    context = {}
    current_user = get_object_or_404(CustomerInfo, user=request.user)
    current_user.update_user_status()  # Make sure their paid period is not up
    if current_user.current_outstanding_balance > 0 or not current_user.this_period_paid:
        return render(request, 'Toolshop/fees_overdue.html', context)
    tool = get_object_or_404(Tool, pk=id)
    tool.is_checked_out = True
    tool.times_checked_out += 1
    tool.date_checked_out = timezone.now()
    tool.who_checked_out = request.user.username
    current_user.num_currently_checked_out += 1
    tool.save()
    current_user.save()

    return render(request, 'Toolshop/redirect.html', context)


def update_user_info(request):
    user = request.user
    user.customerinfo.update_user_status()  # Make sure their paid period is not up
    first_name = request.POST.get('firstName')
    last_name = request.POST.get('lastName')
    address = request.POST.get('address')
    phone_number = request.POST.get('phone')
    email_address = request.POST.get('email')
    password_1 = request.POST.get('psw')
    password_2 = request.POST.get('psw-repeat')

    if password_1 != password_2:
        return HttpResponseRedirect(reverse('Toolshop:updateError'))
    elif phone_number is None:
        return HttpResponseRedirect(reverse('Toolshop:updateError'))
    elif phone_number == "":
        return HttpResponseRedirect(reverse('Toolshop:updateError'))
    elif first_name is None or last_name is None or address is None or email_address is None or password_1 is None:
        return HttpResponseRedirect(reverse('Toolshop:updateError'))
    elif first_name == "" or last_name == "" or address == "" or email_address == "" or password_1 == "":
        return HttpResponseRedirect(reverse('Toolshop:updateError'))
    elif len(first_name) > 30 or len(last_name) > 30 or len(email_address) > 50:
        return HttpResponseRedirect(reverse('Toolshop:updateError'))
    elif len(password_1) < 8 or len(password_1) > 30:
        return HttpResponseRedirect(reverse('Toolshop:updateError'))

    user.first_name = first_name
    user.last_name = last_name
    user.email = email_address
    user.customerinfo.address = address
    user.customerinfo.phone_num = phone_number
    user.set_password(password_1)

    user.save()
    user.customerinfo.save()
    # Always return an HttpResponseRedirect after successfully dealing
    # with POST data. This prevents data from being posted twice if a
    # user hits the Back button.
    return HttpResponseRedirect(reverse('Toolshop:redirect'))


def submit_message(request):
    first_name = request.POST.get('firstname')
    last_name = request.POST.get('lastname')
    email_address = request.POST.get('emailAddress')
    subject = request.POST.get('subject')
    message = request.POST.get('textBody')

    if first_name is None or last_name is None or email_address is None or subject is None or message is None:
        return HttpResponseRedirect(reverse('Toolshop:error'))
    elif first_name == "" or last_name == "" or email_address == "" or subject == "" or message == "":
        return HttpResponseRedirect(reverse('Toolshop:error'))
    elif len(first_name) > 30 or len(last_name) > 30 or len(email_address) > 50:
        return HttpResponseRedirect(reverse('Toolshop:error'))
    elif len(subject) > 100 or len(message) > 1000:
        return HttpResponseRedirect(reverse('Toolshop:error'))

    new_message = Message(first_name=first_name, last_name=last_name,
                          email=email_address, subject=subject,
                          message=message)
    new_message.save()
    # Always return an HttpResponseRedirect after successfully dealing
    # with POST data. This prevents data from being posted twice if a
    # user hits the Back button.
    return HttpResponseRedirect(reverse('Toolshop:redirect'))


def submission_error(request):
    context = {}
    return render(request, 'Toolshop/submission_error.html', context)


def update_error(request):
    context = {}
    return render(request, 'Toolshop/update_error.html', context)


def redirection_page(request):
    context = {}
    return render(request, 'Toolshop/redirect.html', context)


@permission_required('admin.can_add_log_entry')
def database_upload(request):
    template = "Toolshop/database_upload.html"
    prompt = {
        'order': 'Order of CSV should be category, name, value, quantity, on-hand, checked-out'
    }
    if request.method == "GET":
        return render(request, template, prompt)
    csv_file = request.FILES['file']
    if not csv_file.name.endswith('.csv'):
        messages.error(request, "This is not a CSV file")
    data_set = csv_file.read().decode('UTF-8')
    io_string = io.StringIO(data_set)
    next(io_string)
    for column in csv.reader(io_string, delimiter=','):
        print(int(column[3]))
        for i in range(int(column[3])):
            print("creating " + column[1])
            created = Tool(
                category=column[0],
                name=column[1],
                cost=column[2],
                times_checked_out=0
            )
            created.save()
    context = {

    }
    return render(request, template, context)


'''
THESE ARE THE EMPLOYEE VIEWS.
THIS IS A DIFFERENT PART OF THE WEBSITE, ONLY ACCESSIBLE BY EMPLOYEES
'''


@permission_required('user.is_staff')
def reports_main(request):
    context = {}
    return render(request, 'Toolshop/reports_main.html', context)


@permission_required('user.is_staff')
def reports_users(request):
    users_list = User.objects.all()
    for user in users_list:
        user.customerinfo.update_user_status()  # Make sure their paid period is not up
    context = {
        'users_list': users_list,
    }
    return render(request, 'Toolshop/reports_users.html', context)


@permission_required('user.is_staff')
def specific_user(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    user.customerinfo.update_user_status()  # Make sure their paid period is not up
    context = {
        "user": user,
    }
    return render(request, 'Toolshop/reports_specificuser.html', context)


@permission_required('user.is_staff')
def specific_tool(request, tool_id):
    tool = get_object_or_404(Tool, pk=tool_id)
    context = {
        "tool": tool,
    }
    return render(request, 'Toolshop/reports_specifictool.html', context)


@permission_required('user.is_staff')
def reports_tools(request, sort_by):
    if sort_by == "checked_out":
        tools_list = Tool.objects.filter(is_checked_out=True)
    elif sort_by == "popularity":
        tools_list = Tool.objects.order_by("-times_checked_out")
    else:
        tools_list = Tool.objects.all()

    context = {
        'tools_list': tools_list,
    }
    return render(request, 'Toolshop/reports_tools.html', context)


@permission_required('user.is_staff')
def check_in_page(request):
    tools_list = Tool.objects.filter(is_checked_out=True)
    context = {
        'tools_list': tools_list,
    }
    return render(request, 'Toolshop/reports_checkin.html', context)


@permission_required('user.is_staff')
def add_tool_page(request):
    context = {}
    return render(request, 'Toolshop/reports_payfees.html', context)


@permission_required('user.is_staff')
def check_in(request, tool_id):
    tool = get_object_or_404(Tool, pk=tool_id)
    current_user = get_object_or_404(CustomerInfo, user=request.user)
    current_user.update_user_status()  # Make sure their paid period is not up
    tool.is_checked_out = False
    tool.date_checked_out = None
    tool.who_checked_out = ""

Dan's Toolshop Server/cs3460/Toolshop/templates/Toolshop/contact.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
<title>Dan's Tool Rentals</title>
<meta charset="UTF-8">
  {% load static %}
  <link rel="stylesheet" href="{% static 'Toolshop/layout.css' %}">
  <link rel="shortcut icon" type="image/png" href="{% static 'Toolshop/favicon.ico' %}"/>
</head>
<body>
<div class="wrapper row1">
  <header id="header" class="clear">
    <div id="hgroup">
      <h1><a href="{% url 'Toolshop:index' %}">Dan's Tool Shop
      <img src="{% static 'Toolshop/logo.jpg' %}" style="width:15%"></a></h1>
    </div>
      <fieldset>
        <div style="padding-right: 0px">
          <button class="menuButtons" style="height: 29.4px" "font:bold;"> <a href="{% url 'Toolshop:account' %}">Account</a> </button>
        </div>
        <div style="padding-right: 110px">
          <button class="menuButtons" style="height: 29.4px" "font:bold;"> <a href="{% url 'Toolshop:reserve' %}">Reserve a Tool</a> </button>
        </div>
      </fieldset>

    <nav>
      <ul>
        <li><a href="{% url 'Toolshop:index' %}">Home</a></li>
        <li><a href="{% url 'Toolshop:tools' %}">Our Tools</a></li>
        <li><a href="{% url 'Toolshop:projects' %}">Our Projects</a></li>
        <li><a href="{% url 'Toolshop:contact' %}">Contact Us!</a></li>
        <li><a href="{% url 'Toolshop:reports_main' %}">Employee Portal</a></li>
      </ul>
    </nav>
  </header>
</div>


<div class="wrapper row2">
  <div id="container" class="clear">
    <div>
      <h2>Drop by our store anytime!</h2>
      <br><br>
      <p>We're located locally at: </p>
      <p>1040 Main St, Logan, UT 84341</p>
      <br><br>
      <p>Monday - Friday     -     8:00am - 9:00pm</p>
      <p>Saturday            -     8:00am - 10:00pm</p>
      <p>Sunday              -     Closed</p>
      <br><br>
      <p>Note: Store hours may be affected by holidays and/or COVID-19</p>
      <br><br>
  </div>
    <div class="container" style="border:1px solid #ccc">
        <form action="{% url 'Toolshop:submitMessage'%}" method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <div class="container">

            <label for="fname">First Name</label>
            <input type="text" id="fname" name="firstname" class="text-input">
            <br>
            <br>

            <label for="lname">Last Name</label>
            <input type="text" id="lname" name="lastname" class="text-input">
            <br>
            <br>
            
            <label for="email">Email</label>
            <input type="email" id="email" name="emailAddress" class="text-input">
            <br>
            <br>
            
            <label for="subject">Subject</label>
            <input type="text" id="subject" name="subject" class="text-input">
            <br>
            <br>

            <textarea id="textBody" name="textBody" placeholder="Ask us questions and we'll get back to you!" style="height:200px"></textarea>
            <br>
            <br>

            <input type="submit" value="Submit" class="text-input">
            <br><br>
          </div>
        </form>
        <div style="width:100%;height:300px;">
          <img src="{% static 'Toolshop/map.jpg' %}" style="width:100%;height:100%;">
        </div>

    </div>
  </div>
</div>



<!-- Footer -->
<div class="wrapper row3">
  <footer id="footer" class="clear">
    <p class="fl_left">Copyright &copy; 2020 - All Rights Reserved - <a href="#">DansToolShop.com<br><img src="{% static 'Toolshop/logo.jpg' %}" style="width:15%"> </a></p>
    <p class="fl_right">Template by <a target="_blank" href="https://www.os-templates.com/" title="Free Website Templates">OS Templates</a></p>
  </footer>
</div>
</body>
  <script src="{% static 'Toolshop/script.js' %}"></script>
</html>

Dan's Toolshop Server/cs3460/Toolshop/templates/Toolshop/database_upload.html
{% if messages %}
	{% for message in messages %}
		<div>
			<strong>{{ message|safe }}</strong>
		</div>
	{% endfor %}
{% else %}
{{order}}
<form method='post' enctype= "multipart/form-data">
	{% csrf_token %}
	{{ form.as_p }}
	<label>Upload a file</label>
	<input type='file' name='file'>
	<p> Only accepts CSV files</p>
	<button type='submit'> Upload </button>
	
</form>
{% endif %}

Dan's Toolshop Server/cs3460/Toolshop/templates/Toolshop/entry.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
<title>Dan's Tool Rentals</title>
<meta charset="UTF-8">
  {% load static %}
  <link rel="stylesheet" href="{% static 'Toolshop/layout.css' %}">
  <link rel="shortcut icon" type="image/png" href="{% static 'Toolshop/favicon.ico' %}"/>
</head>
<body>
<div class="wrapper row1">
  <header id="header" class="clear">
    <div id="hgroup">
      <h1><a href="{% url 'Toolshop:index' %}">Dan's Tool Shop
      <img src="{% static 'Toolshop/logo.jpg' %}" style="width:15%"></a></h1>
    </div>
      <fieldset>
        <div style="padding-right: 0px">
          <button class="menuButtons" style="height: 29.4px" "font:bold;"> <a href="{% url 'Toolshop:account' %}">Account</a> </button>
        </div>
        <div style="padding-right: 110px">
          <button class="menuButtons" style="height: 29.4px" "font:bold;"> <a href="{% url 'Toolshop:reserve' %}">Reserve a Tool</a> </button>
        </div>
      </fieldset>

    <nav>
      <ul>
        <li><a href="{% url 'Toolshop:index' %}">Home</a></li>
        <li><a href="{% url 'Toolshop:tools' %}">Our Tools</a></li>
        <li><a href="{% url 'Toolshop:projects' %}">Our Projects</a></li>
        <li><a href="{% url 'Toolshop:contact' %}">Contact Us!</a></li>
        <li><a href="{% url 'Toolshop:reports_main' %}">Employee Portal</a></li>
      </ul>
    </nav>
  </header>
</div>
<!-- content -->
<div class="wrapper row2">
  <div id="container" class="clear">
    <!-- content body -->
    <!-- main content -->

    <div id="homepage">

    </div>
    <!-- / content body -->
  </div>
</div>
<!-- Footer -->
<div class="wrapper row3">
  <footer id="footer" class="clear">
    <p class="fl_left">Copyright &copy; 2020 - All Rights Reserved - <a href="#">DansToolShop.com<br><img src="{% static 'Toolshop/logo.jpg' %}" style="width:15%"> </a></p>
    <p class="fl_right">Template by <a target="_blank" href="https://www.os-templates.com/" title="Free Website Templates">OS Templates</a></p>
  </footer>
</div>
</body>
  <script src="{% static 'Toolshop/script.js' %}"></script>
</html>

Dan's Toolshop Server/cs3460/Toolshop/templates/Toolshop/reports_payfees.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
<title>Dan's Tool Rentals</title>
<meta charset="UTF-8">
  {% load static %}
  <link rel="stylesheet" href="{% static 'Toolshop/layout.css' %}">
  <link rel="shortcut icon" type="image/png" href="{% static 'Toolshop/favicon.ico' %}"/>
</head>
<body>
<div class="wrapper row1">
  <header id="header" class="clear">
    <div id="hgroup">
      <h1><a href="{% url 'Toolshop:index' %}">Dan's Employee Portal
      <img src="{% static 'Toolshop/logo.jpg' %}" style="width:15%"></a></h1>
    </div>

    <nav>
      <ul>
        <li><a href="{% url 'Toolshop:index' %}">Main Website</a></li>
        <li><a href="{% url 'Toolshop:reports_users' %}">Users</a></li>
        <li><a href="{% url 'Toolshop:reports_tools' sort_by='all' %}">Tools</a></li>
        <li><a href="{% url 'Toolshop:reports_tools' sort_by='checked_out' %}">Tools (Checked out)</a></li>
        <li><a href="{% url 'Toolshop:reports_tools' sort_by='popularity' %}">Tools (Popularity)</a></li>
        <li><a href="{% url 'Toolshop:check_in' %}">Check Tools In</a></li>
        <li><a href="{% url 'Toolshop:pay_fee_page' %}">Pay Fees</a></li>
      </ul>
    </nav>
  </header>
</div>
<!-- content -->
<div class="wrapper row2">
  <div id="container" class="clear">
    <!-- content body -->
    <!-- main content -->
    <div id="homepage">
      <h1> Fees Page:</h1>
      <p>Once a user has paid in person, click on the link by their name to mark fees as paid.</p>
      {% if users_list %}
		<table cellspacing="20">
          <tr>
            <th>Username:</th>
            <th>First Name:</th>
            <th>Last Name:</th>
            <th>Fees Due: </th>
            <th>This Period Paid? </th>
          </tr>
			{% for user in users_list %}
          <tr>
            <td><a href="{% url 'Toolshop:specific_user' user.id %}">{{user.username}}</a></td>
            <td>{{user.first_name}}</td>
            <td>{{user.last_name}}</td>
            {% if user.customerinfo.current_outstanding_balance > 0 %}
              <td style="color:red;">
                <a href="{% url 'Toolshop:pay_fee' user.id %}">{{user.customerinfo.current_outstanding_balance}}</a>
              </td>
            {% else %}
              <td>
                {{user.customerinfo.current_outstanding_balance}}
              </td>
            {% endif %}
            <td>
              {% if user.customerinfo.this_period_paid %}
              Yes.
              {% else %}
              <a href="{% url 'Toolshop:pay_period' user.id %}">No.</a>
              {% endif %}
            </td>
          </tr>
			{% endfor %}
		</table>
		{% else %}
    		<p>No users found.</p>
		{% endif %}
    </div>
    <!-- / content body -->
  </div>
</div>
<!-- Footer -->
<div class="wrapper row3">
  <footer id="footer" class="clear">
    <p class="fl_left">Copyright &copy; 2020 - All Rights Reserved - <a href="#">DansToolShop.com<br><img src="{% static 'Toolshop/logo.jpg' %}" style="width:15%"> </a></p>
    <p class="fl_right">Template by <a target="_blank" href="https://www.os-templates.com/" title="Free Website Templates">OS Templates</a></p>
  </footer>
</div>
</body>
  <script src="{% static 'Toolshop/script.js' %}"></script>
</html>

Dan's Toolshop Server/cs3460/Toolshop/templates/Toolshop/reservation.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
<title>Dan's Tool Rentals</title>
<meta charset="UTF-8">
  {% load static %}
  <link rel="stylesheet" href="{% static 'Toolshop/layout.css' %}">
  <link rel="shortcut icon" type="image/png" href="{% static 'Toolshop/favicon.ico' %}"/>
</head>
<body>
<div class="wrapper row1">
  <header id="header" class="clear">
    <div id="hgroup">
      <h1><a href="{% url 'Toolshop:index' %}">Dan's Tool Shop
      <img src="{% static 'Toolshop/logo.jpg' %}" style="width:15%"></a></h1>
    </div>
      <fieldset>
        <div style="padding-right: 0px">
          <button class="menuButtons" style="height: 29.4px" "font:bold;"> <a href="{% url 'Toolshop:account' %}">Account</a> </button>
        </div>
        <div style="padding-right: 110px">
          <button class="menuButtons" style="height: 29.4px" "font:bold;"> <a href="{% url 'Toolshop:reserve' %}">Reserve a Tool</a> </button>
        </div>
      </fieldset>

    <nav>
      <ul>
        <li><a href="{% url 'Toolshop:index' %}">Home</a></li>
        <li><a href="{% url 'Toolshop:tools' %}">Our Tools</a></li>
        <li><a href="{% url 'Toolshop:projects' %}">Our Projects</a></li>
        <li><a href="{% url 'Toolshop:contact' %}">Contact Us!</a></li>
        <li><a href="{% url 'Toolshop:reports_main' %}">Employee Portal</a></li>
      </ul>
    </nav>
  </header>
</div>
<!-- content -->
<div class="wrapper row2">
  <div id="container" class="clear">
    <!-- content body -->
    <!-- main content -->
    <div id="homepage">
      <form action="{% url 'Toolshop:reserve'%}subset" method="post">
            {% csrf_token %}
            <input type="text" name="query" value="" size="32" class="text-input">
            <input type="submit" value="Search our tools..." />
        </form>
      {% if tools_list %}
		<table cellspacing="20">
          <tr>
            <th>Name:</th>
            <th>Category:</th>
            <th></th>
          </tr>
			{% for tool in tools_list %}
          <tr>
            <td>{{tool.name}}</td>
            <td>{{tool.category}}</td>
            {% if tool.is_checked_out %}
            <td>Not Currently Available</td>
            {% else %}
            <td>
                <a href="{% url 'Toolshop:makeReservation' tool.id %}">Available.  Click here to reserve.</a>
            </td>
            {% endif %}
          </tr>
			{% endfor %}
		</table>
		{% else %}
    		<p>No tools found.</p>
		{% endif %}
    </div>
    <!-- / content body -->
  </div>
</div>
<!-- Footer -->
<div class="wrapper row3">
  <footer id="footer" class="clear">
    <p class="fl_left">Copyright &copy; 2020 - All Rights Reserved - <a href="#">DansToolShop.com<br><img src="{% static 'Toolshop/logo.jpg' %}" style="width:15%"> </a></p>
    <p class="fl_right">Template by <a target="_blank" href="https://www.os-templates.com/" title="Free Website Templates">OS Templates</a></p>
  </footer>
</div>
</body>
  <script src="{% static 'Toolshop/script.js' %}"></script>
</html>